name: Deploy Django to Azure VM

on:
  push:
    tags:
      - "v*"   # Trigger on any tag starting with "v"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Upload code to Azure VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          source: "."
          target: "/home/${{ secrets.AZURE_USER }}/attendance-app"

      - name: Deploy on VM
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd ~/attendance-app
            git fetch --tags
            TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
            git checkout $TAG

            # Activate virtualenv and install dependencies
            source venv/bin/activate
            pip install -r requirements.txt

            # Run migrations and collect static files
            python manage.py migrate --noinput
            python manage.py collectstatic --noinput

            # Restart Gunicorn and Nginx
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
